name: Deploy - Prod

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/**

jobs:
  trigger_prod:
    uses: ./.github/workflows/_deploy.yaml
    with:
      environment: prod
    secrets:
      OCI_VM_IP: ${{ secrets.OCI_VM_IP }}
      OCI_SSH_PRIVATE_KEY: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
