name: Deploy - Dev

on:
  push:
    branches:
      - dev
    paths-ignore:
      - .github/workflows/**

## Adds random comment
jobs:
  trigger_dev:
    uses: ./.github/workflows/_deploy.yaml
    with:
      environment: dev
    secrets:
      OCI_VM_IP: ${{ secrets.OCI_VM_IP }}
      OCI_SSH_PRIVATE_KEY: ${{ secrets.OCI_SSH_PRIVATE_KEY }}
